apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqlb
spec:
  serviceName: mysqlb
  replicas: 1
  selector:
    matchLabels:
      app: mysqlb
  template:
    metadata:
      labels:
        app: mysqlb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: private
                operator: In
                values:
                - "true"
      containers:
      - name: mysqlb
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/notefort-mysqlb:${IMAGE_TAG}
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: sqlb-vct
          mountPath: /var/lib/mysql

        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password

        resources:
          requests:
            cpu: "250m"      # 0.25 vCPU, enough for small MySQL workload
            memory: "256Mi"  # 256MB of RAM, should be sufficient for a small DB
          limits:
            cpu: "500m"      # 0.5 vCPU, allows for occasional CPU spikes
            memory: "512Mi"  # 512MB of RAM, MySQL can handle some bursts

        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost"]
          initialDelaySeconds: 30
          periodSeconds: 30
          
  volumeClaimTemplates:
  - metadata:
      name: sqlb-vct
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: sqlb-sc
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sqlb-sc
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Delete  # deleting the PVC will ALSO delete the PV, if preferred change to Retain if you want to keep the PV
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Service
metadata:
  name: mysqlb
spec:
  clusterIP: None  # for stable hostname (mysqlb-0.mysqlb.default.svc.cluster.local)
  selector:
    app: mysqlb
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mysqlb-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mysqlb
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: mysqlb
      minAllowed:
        cpu: "125m"    
        memory: "128Mi"   
      maxAllowed:
        cpu: "750m"    
        memory: "640Mi"