{{- range .Values.mysqlInstances }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .storageClass }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
{{- end }}
