{{- range .Values.mysqlInstances }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .name }}-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .name }}
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .name }}
      minAllowed:
        cpu: "125m"
        memory: "128Mi"
      maxAllowed:
        cpu: "750m"
        memory: "640Mi"
{{- end }}
