awsAccountId: "<AWS_ACCOUNT_ID>"
awsRegion: "<AWS_REGION>"

mysqlInstances:
  - name: mysqla
    volumeClaim: "notefort-sqla-vct"
    storageClass: "notefort-sqla-sc"
    initScript: |
      CREATE DATABASE IF NOT EXISTS mysqla;
      USE mysqla;
      CREATE TABLE IF NOT EXISTS main (
          id INT AUTO_INCREMENT PRIMARY KEY,
          msg VARCHAR(255) NOT NULL
      );
  - name: mysqlb
    volumeClaim: "notefort-sqlb-vct"
    storageClass: "notefort-sqlb-sc"
    initScript: |
      CREATE DATABASE IF NOT EXISTS mysqlb;
      USE mysqlb;
      CREATE TABLE IF NOT EXISTS main (
          id INT AUTO_INCREMENT PRIMARY KEY,
          ida INT NOT NULL,
          msgcp VARCHAR(255) NOT NULL
      );

nodejsServices:
  - name: nodejsa
    port: 4000
    dbHost: "mysqla"
    dbName: "mysqla"
    dbUser: "root"
    imageRepo: "notefort-nodejsa"
    imageTag: 8d48fbb
  - name: nodejsb
    port: 5000
    dbHost: "mysqlb"
    dbName: "mysqlb"
    dbUser: "root"
    imageRepo: "notefort-nodejsb"
    imageTag: f5cfea9
