name: Backend - Create
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      ASM_PARAMETER_NAME: "NOTEFORT_BUCKET_NAME"
      DYNAMODB_TABLE: "notefort-locks"
      PREFIX: "notefort-state"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.GH_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Generate Unique S3 Bucket Name
        run: |
          UNIQUE_ID=$(uuidgen | tr '[:upper:]' '[:lower:]' | cut -c1-8)
          BUCKET_NAME="$PREFIX-$UNIQUE_ID"
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
          echo "Generated bucket name: $BUCKET_NAME"

      - name: Create S3 Bucket
        run: |
          aws s3api create-bucket \
            --bucket $BUCKET_NAME \
            --region ${{ secrets.AWS_REGION }} \

          aws s3api put-bucket-tagging \
            --bucket $BUCKET_NAME \
            --tagging "TagSet=[{Key=Name,Value=notefort-state}]"

      - name: Set S3 Public Access Block
        run: |
          aws s3api put-public-access-block \
            --bucket $BUCKET_NAME \
            --public-access-block-configuration \
              BlockPublicAcls=true,BlockPublicPolicy=true,IgnorePublicAcls=true,RestrictPublicBuckets=true

      - name: Create DynamoDB Table
        run: |
          aws dynamodb create-table \
            --table-name $DYNAMODB_TABLE \
            --attribute-definitions AttributeName=LockID,AttributeType=S \
            --key-schema AttributeName=LockID,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST \
            --tags Key=Name,Value=notefort-lock-table

      - name: Save Bucket Name to Parameter Store
        run: |
          aws ssm put-parameter \
            --name $ASM_PARAMETER_NAME \
            --value $BUCKET_NAME \
            --type String \
            --overwrite

          echo "BACKEND RESOURCES CREATED SUCCESSFULLY"
          