name: Infrastructure - Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      BUCKET_ASM_PARAMETER_NAME: "notefort-bucket-name"
      DYNAMODB_TABLE_NAME: "notefort-locks"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.GH_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Fetch Bucket Name from ASM
        run: |
          BUCKET_NAME=$(aws ssm get-parameter --name $BUCKET_ASM_PARAMETER_NAME --query "Parameter.Value" --output text)
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

      - name: Create backend.tf file dynamically
        run: |
          BACKEND_FILE="./operations/terraform/backend.tf"
          truncate -s 0 $BACKEND_FILE
          cat <<EOT > $BACKEND_FILE
          terraform {
            backend "s3" {
              bucket = "${BUCKET_NAME}"
              key    = "terraform.tfstate"
              region = "${{ secrets.AWS_REGION }}"
              dynamodb_table = "${DYNAMODB_TABLE_NAME}"
            }
          }
          EOT

      - name: Destroy Infrastructure   
        run: |
          cd ./operations/terraform
          terraform init
          terraform destroy -var-file="terraform.tfvars" -auto-approve

          echo "INFRASTRUCTURE DESTROYED SUCCESSFULLY"